services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:jammy
    container_name: mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - maria_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=1234
    expose:
      - 3306
    networks:
      - lan
  nc:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 82:80
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped
    networks:
      - wan
      - lan
    links:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    restart: unless-stopped
    networks:
      - wan
      - lan
volumes:
  maria_data:
  nc_data:
networks:
  # The presence of these objects is sufficient to define them
  lan: {}
  wan: {}