# pacocua
# ene-2023
# SERVICIO NEXTCLOUD: 
# ----------------
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:jammy
    container_name: mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    restart: unless-stopped
    volumes:
      - db-vol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 82:80
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped
volumes:
  nextcloud:
  db-vol: